### ISSUE TITLE
为什么我呢action没办法触发呀

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#1]
如题，设置了测试的cron为'0 7 * * *'，但是刚才15:00了还是没有触发，secret都添加了，也手动action触发了一次

**Comment by 838239178** [comment]
> 如题，设置了测试的cron为'0 7 * * *'，但是刚才15:00了还是没有触发，secret都添加了，也手动action触发了一次

那你手动触发后有显示错误日志吗，显示了什么

**Comment by dawnli-github** [comment]
原本是没有的，但是刚才好像那边登录有点崩溃登不上去？你可以看看我的action

**Comment by dawnli-github** [comment]
似乎可以正常触发了，只是常常会有延迟不会准时触发？然后验证码容易有出错的问题。

**Comment by 838239178** [comment]
> 原本是没有的，但是刚才好像那边登录有点崩溃登不上去？你可以看看我的action

验证码识别有时候会失败，我待会儿加上失败重试的代码应该会好一点

**Comment by dawnli-github** [comment]
可以正常触发了，原来会有延迟。你改完以后我是用pull request吗？有没有可能加一个防止flow挂起的workflow？

**Comment by 838239178** [comment]
@dawnli-github  已上传最新代码，请重新fork项目

**Comment by 838239178** [comment]
> 可以正常触发了，原来会有延迟。你改完以后我是用pull request吗？有没有可能加一个防止flow挂起的workflow？

还是使用手动触发和定时触发两种方式
