### ISSUE TITLE
ocr类型不存在

### ISSUE THREAD

**Issue by zhypocritical** [838239178/tk-auto-study#10]
Run python3 workflow.py
[INFO]:自动学习开始
Error: :ocr类型不存在,请更换类型
Error: Process completed with exit code 255.

![9H`{KXZW PWFD2TMD NDE$G](https://user-images.githubusercontent.com/72993101/130554528-11fa51df-9e77-4c2e-af07-ae02446c7ed5.png)
上次的还能用，看见更新了，顺手更新了下，然后就不能用了。
emmmm 不会更换类型

**Comment by 838239178** [comment]
啊。。应该是有默认对接的，出了点问题，你可以先手动添加一个secret OCR_TYPE为baidu_image

**Comment by zhypocritical** [comment]
> 啊。。应该是有默认对接的，出了点问题，你可以先手动添加一个secret OCR_TYPE为baidu_image
emmm是在
3Q  可以了

**Comment by 838239178** [comment]
已修复
