### ISSUE TITLE
关于腾讯云函数部署无法调用tesseract

### ISSUE THREAD

**Issue by Githubsanae** [838239178/tk-auto-study#101]
### 内容

用腾讯云函数python3.7`部署代码，相关依赖已安装完成，终端运行正常，但是用触发器时不能调用tesseract，提示如下：
获取验证码失败，原因:tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by 838239178** [comment]
pytesseract？

**Comment by 838239178** [comment]
定时任务执行的终端有可能和控制台用的不一样 比如环境变量配置在bash的.bashrc但是定时任务用的sh之类的

**Comment by Githubsanae** [comment]
尝试解决，但是没有相关案例，最后选择了azure
