### ISSUE TITLE
使用v2版本报错 'dict' object has no attribute 'token'

### ISSUE THREAD

**Issue by hxp1999** [838239178/tk-auto-study#110]
### 使用的Python版本

3.9

### 使用的发行版本

v2

### 运行平台

local/server

### 问题描述

填写config.json如下后运行报错
![图片](https://user-images.githubusercontent.com/20153079/194550445-2ac06b70-b095-4190-8311-09c0d8a5a671.png)

### 运行日志

![图片](https://user-images.githubusercontent.com/20153079/194550546-ba103984-6941-4e18-b669-dbd7fbaebee4.png)

**Comment by 838239178** [comment]
已更新，配置文件重新更新一下
