### ISSUE TITLE
为什么感觉是这个f识别不出来

### ISSUE THREAD

**Issue by Aiso0** [838239178/tk-auto-study#22]
![图片](https://user-images.githubusercontent.com/86371645/139573375-218e48ec-d786-45e6-93db-6fa652f5e0bf.png)

**Comment by 838239178** [comment]
python3?

**Comment by Aiso0** [comment]
没错 python3.7

**Comment by Aiso0** [comment]
![图片](https://user-imagexzithubusercontent.com/86371645/139574698-916752cc-7e1a-4d58-8d2b-a57f1348ca5f.png)
改了一下就变成这样了。。。

**Comment by Aiso0** [comment]
![图片](https://user-images.githubusercontent.com/86371645/139574709-977f54cf-a171-45e7-a0a5-1b47d53ce4b4.png)

**Comment by 838239178** [comment]
请检查你的配置文件

**Comment by Aiso0** [comment]
配置文件 按道理来说应该没问题，我在本地是可以的

**Comment by 838239178** [comment]
Github secret 的名字不能有误 仔细阅读readme检查一下

**Comment by Aiso0** [comment]
搞定了，谢谢 ，我是放在我的服务器里，直接运行main就好，我运行的是workflow
