### ISSUE TITLE
[BUG] GitHubAction上无法打卡

### ISSUE THREAD

**Issue by HolyDomain** [838239178/tk-auto-study#38]
## 问题描述

rror: :发生未知异常(请截图日志发issue)：HTTPSConnectionPool(host='m.fjcyl.com', port=443): Max retries exceeded with url: /validateCode?0.123123&width=58&height=19&num=4 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb861134ee0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

## 使用的版本

GitHub actions

**python:**[e.g. 3.7]
**version:**[e.g. 1.2.2]

## 完整的运行日志

```text

```

**Comment by 838239178** [comment]
官方服务器维护 现在已经恢复

**Comment by 838239178** [comment]
很可能是官方把Github的IP禁止了

**Comment by HsukqiLee** [comment]
我也遇到了这个问题
![6bee5d6282b091e4](https://user-images.githubusercontent.com/79034142/147107270-82c61336-c743-4f30-8e02-a81571c5f890.png)

**Comment by HsukqiLee** [comment]
建议通过php反代官方服务器的方法临时解决。
顺带提一句，NGINX的反代貌似会报502。

**Comment by 838239178** [comment]
@HsukqiLee 这个需要额外提供服务器吧，如果被逮到了也可能会把代理服务器给ban了😞

**Comment by HsukqiLee** [comment]
> @HsukqiLee 这个需要额外提供服务器吧，如果被逮到了也可能会把代理服务器给ban了😞

用中国大陆的服务器应该不会被发现（笑）
就正常进行登录、学团课，不至于。
另外GitHub好像也有那种，公共的代理IP池，可以考虑一下。但是这种貌似也是境外的，用了几次可能就会被ban

**Comment by yating1022** [comment]
可以使用自己的代理ip吗，不然老是会失败

**Comment by 838239178** [comment]
> 可以使用自己的代理ip吗，不然老是会失败

如果自己有服务器建议直接在服务器上定时运行

**Comment by yating1022** [comment]
> 
我是小白一个，大神你的说明页只说了这种方法，没教程，我服务器不会搞

**Comment by 838239178** [comment]
> 我是小白一个，大神你的说明页只说了这种方法，没教程，我服务器不会搞
那我在写一点说明吧

**Comment by yating1022** [comment]
> > 我是小白一个，大神你的说明页只说了这种方法，没教程，我服务器不会搞
> 
> 那我在写一点说明吧

  大哥，搞了之后我试着运行了一下main.py，出现下面这个，我昨天自己尝试的时候也是这个
File "main.py", line 1, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "/root/tk-auto-study/proxy_module/proxy_fetcher.py", line 4, in <module>
    from .proxy import fetchers
  File "/root/tk-auto-study/proxy_module/proxy.py", line 3, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

**Comment by HolyDomain** [comment]
> > > 我是小白一个，大神你的说明页只说了这种方法，没教程，我服务器不会搞
> > 
> > 
> > 那我在写一点说明吧
> 
> 大哥，搞了之后我试着运行了一下main.py，出现下面这个，我昨天自己尝试的时候也是这个 File "main.py", line 1, in from proxy_module.proxy_fetcher import ProxyFecher File "/root/tk-auto-study/proxy_module/proxy_fetcher.py", line 4, in from .proxy import fetchers File "/root/tk-auto-study/proxy_module/proxy.py", line 3, in from lxml import etree ModuleNotFoundError: No module named 'lxml'

你没装依赖，在项目目录运行`pip install -r requirements.txt`一下

**Comment by yating1022** [comment]
> 

现在是这个报错，是不是脚本还是调用了代理模块。
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from proxy_module.proxy_fetcher import ProxyFecher
  File "/root/tk-auto-study/proxy_module/proxy_fetcher.py", line 7, in <module>
