### ISSUE TITLE
[BUG]本地环境 多用户识别失败

### ISSUE THREAD

**Issue by HsukqiLee** [838239178/tk-auto-study#42]
## 问题描述
使用国内服务器（上海）git clone代码到本地，仅配置config.json中的username和pwd，未配置ext_users时，依然会被识别为两个用户，会报错误，提示部分用户信息异常，消息推送“部分用户打卡失败”；原有的单用户可以正常打卡。

## 使用的版本

**python:**[3.9]
**version:**[1.2.3]

## 完整的运行日志
![Screenshot_20211228_125846_edit_255304142272062](https://user-images.githubusercontent.com/79034142/147578360-63a22750-3adc-495d-bf4a-c2a4b67434ac.jpg)
![-30fa56e67d5da607](https://user-images.githubusercontent.com/79034142/147578483-8e96c943-2937-49f2-8532-fe6f886f413c.png)

**Comment by 838239178** [comment]
这边1.2.4没有问题，在 `extUsers: []` 或不存在extUsers是不会进行多人打卡的

**Comment by 838239178** [comment]
这边1.2.4没有问题，在 `extUsers: []` 或不存在extUsers是不会进行多人打卡的

**Comment by HsukqiLee** [comment]
找到问题原因了
我直接将信息填入了config.json.bak并将其重命名，因此参数中有模板里的
`"extUsers": [
    {
      "username": "",
      "pwd": ""
    }
  ]`
感谢您的回复。
