### ISSUE TITLE
[BUG]本地配置无法运行

### ISSUE THREAD

**Issue by blackdoge** [838239178/tk-auto-study#43]
![46b15890375ece9fdf051cbbb868088](https://user-images.githubusercontent.com/26867428/147824811-43f41eba-1395-488a-863a-14fe18d1b2e1.png)
## 使用的版本

**python:**[e.g. 3.7]
**version:**[e.g. 1.2.2]

## 完整的运行日志

```text

```

**Comment by 838239178** [comment]
你配置文件有问题

**Comment by blackdoge** [comment]
谢谢，重新改了下可以了
