### ISSUE TITLE
[BUG]请问一下，这个是怎么回事

### ISSUE THREAD

**Issue by wmkai** [838239178/tk-auto-study#44]
## 使用的版本

**python:**[e.g. 3.7]
**version:**[e.g. 1.2.2]

## 完整的运行日志

```text

```
![image](https://user-images.githubusercontent.com/39148461/147845508-84ebbab1-344c-4e34-ad30-f45a0e73d291.png)

**Comment by 838239178** [comment]
你百度ocr账号可能有问题
