### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yymade** [838239178/tk-auto-study#51]
## 使用的版本

**python:**[e.g. 3.7]
**version:**[e.g. 1.2.2]
配置了"extUsers"，但是只读最后一个账号
"extUsers": [
    {
     "username":"test1","pwd":"test1","username":"test2","pwd":"test2"
    }    
  ]

日志：[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:使用 OCR baidu_image
[INFO]:开始多人打卡，人数2
[INFO]:正在登录尾号est2

**Comment by 838239178** [comment]
```json
"extUsers": [
      {
          "username":"test1",
          "pwd":"test1"
      },
     {
          "username":"test1",
          "pwd":"test1"
      }
]
```

**Comment by yymade** [comment]
收到，非常感谢
