### ISSUE TITLE
[询问] 本地启动但开启了代理模式

### ISSUE THREAD

**Issue by MnKoLee** [838239178/tk-auto-study#69]
![image](https://user-images.githubusercontent.com/84967153/166181791-d489e1bd-8430-49f9-a9d8-e708f76a29aa.png)
本地试着运行一直获取最新代理 然后测试 但是每个代理都是不可用的

**Comment by 838239178** [comment]
不知道你用的是不是最近的。直接运行main.py应该是不会走代理的。你可以在检查一下代码。

**Comment by MnKoLee** [comment]
![image](https://user-images.githubusercontent.com/84967153/166191242-aca6a7d7-daa5-44c6-961e-4e3a58c28664.png)
挂载到服务器上 现在就是第一次运行走了很久的代理然后成功了 但是第二次运行就会这样

**Comment by MnKoLee** [comment]
仅改过json文件

**Comment by 838239178** [comment]
我之前不小心改过了 你把main.py最后一行的两个True删掉一个

**Comment by MnKoLee** [comment]
是这样么 十分感谢作者 发自内心






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "838239178/tk-auto-study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [838239178/tk-auto-study] [询问] 本地启动但开启了代理模式 (Issue #69)





 
Closed #69.

**Comment by MnKoLee** [comment]
可行了 就是消息不会推送成功的消息 只会推送失败的 然后它每次多次输入手机号 所以就会推那个输入手机号失败的消息给我 用的是pushplus

**Comment by MnKoLee** [comment]
我看懂了 谢谢作者
