### ISSUE TITLE
GitHub Actions 配置文件变量错误

### ISSUE THREAD

**Issue by NERVEbing** [838239178/tk-auto-study#7]
- name: auto study
      env:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PWD}}
        pubKey: ${{secrets.PUB_KEY}}
        ocrSecret: ${{secrets.OCR_API_KEY}}      
        ocrKey: ${{secrets.OCR_SECRET_KEY}}    ## OCR_SECRET_KEY跟OCR_API_KEY填反了

**Comment by 838239178** [comment]
已更改
