### ISSUE TITLE
[BUG] 登录异常 验证码功能回归

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#79]
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:开始单人打卡
[INFO]:正在登录尾号5951
[ERROR]:尾号5951登录失败，原因:登录异常!
[INFO]:尝试重新登录，重试次数0
[ERROR]:尾号5951登录失败，原因:登录异常!
[INFO]:尝试重新登录，重试次数1
[ERROR]:尾号5951登录失败，原因:登录异常!
[INFO]:尝试重新登录，重试次数2
[ERROR]:尾号5951登录失败，原因:登录异常!
[INFO]:尝试重新登录，重试次数3
[ERROR]:尾号5951登录失败，原因:登录异常!
[INFO]:尝试重新登录，重试次数4
[INFO]:消息推送成功
[ERROR]:异常信息: 尾号5951尝试登录失败

**Comment by sumpring** [comment]
是的，全部都是登录异常

**Comment by 838239178** [comment]
看来是被后台识别到不对劲了，我只能说可能要终止项目了
