### ISSUE TITLE
ocr识别建议

### ISSUE THREAD

**Issue by sqlpxc** [838239178/tk-auto-study#82]
### 需求或建议描述

建议使用tesseract来实现ocr识别，看到你这个项目，我自己也写了一份[cyl_auto_punch_rust](https://github.com/sqlpxc/cyl_auto_punch_rust),我发现tesseract的识别成功率非常高，但是由于我对python并不熟悉，很抱歉不能为你提供代码，但是可以提供大体思路，大概就是将验证码二值化然后限定tesseract范围后直接识别就好了。

还有就是建议把我的项目放在readme里，方便普通人更容易使用

### 你希望达到的效果

验证码识别成功率几乎100%，还可以无限制次数使用

我的项目[cyl_auto_punch_rust](https://github.com/sqlpxc/cyl_auto_punch_rust)放在readme里，方便不熟悉python的人使用

### 其他补充

如果有任何疑问都可以问我，我看到了一定会尽可能回答的

**Comment by 838239178** [comment]
tesseract的安装会不会很麻烦

**Comment by sqlpxc** [comment]
我没具体用过，但是我看有个叫pytesseract的包，感觉应该不是很麻烦

**Comment by 838239178** [comment]
> 我没具体用过，但是我看有个叫pytesseract的包，感觉应该不是很麻烦

pytesseract需要调用本地安装的tesseract，tesseract需要自己本地安装一遍

**Comment by sqlpxc** [comment]
> > 我没具体用过，但是我看有个叫pytesseract的包，感觉应该不是很麻烦
> 
> pytesseract需要调用本地安装的tesseract，tesseract需要自己本地安装一遍

其实吧，我可以写一个命令行程序你直接在python调用我的程序，只不过这样就限制了系统了，效率还会不高，你觉得怎么样.

**Comment by 838239178** [comment]
rust不能跨平台吗 
你的rust是使用了tesseract吗？不需要本地安装吗？
如果rust可以直接做到直接调用二进制可执行文件就能识别的话，欢迎你针对性ocr模块提交一个pr 并把“单纯具备ocr功能的rust编译好的二进制文件”作为额外下载项目放到ocr帮助文档中让大家下载。如果可执行文件小于50mb那么也可以直接放下文件目录下

**Comment by sqlpxc** [comment]
> rust不能跨平台吗
> 你的rust是使用了tesseract吗？不需要本地安装吗？
> 如果rust可以直接做到直接调用二进制可执行文件就能识别的话，欢迎你针对性ocr模块提交一个pr 并把“单纯具备ocr功能的rust编译好的二进制文件”作为额外下载项目放到ocr帮助文档中让大家下载。如果可执行文件小于50mb那么也可以直接放下文件目录下

rust可以交叉编译，rust的跨平台你可以类比c++，需要每个平台都编译一遍，我的代码是使用tesseract的c++代码生成了static库，然后在rust里引用的，只不过这是对于开发者而言，需要编译tesseract，但是对于用户而言这并不需要，打包的文件很小，不会超过10m

**Comment by 838239178** [comment]
你可以编译一个纯ocr的文件然后提交一个pr
