### ISSUE TITLE
[WARNING]:获取验证码失败，原因:unknown client id

### ISSUE THREAD

**Issue by dierwang101** [838239178/tk-auto-study#84]
### 内容

感谢作者。我在本地上运行，一直显示【[WARNING]:获取验证码失败，原因:unknown client id】，想问问什么原因。

**Comment by 838239178** [comment]
ocr的apikey和secretkey复制正确吗，这个和百度那边的配置有关系，顺利的话下个版本会加入本地OCR识别

**Comment by ChampionChann** [comment]
> ocr的apikey和secretkey复制正确吗，这个和百度那边的配置有关系，顺利的话下个版本会加入本地OCR识别

百度那边需要购买吗？我创建了一个图片识别的应用后，领取了免费次数，ocr的apikey和secretkey是直接复制过来的
![image](https://user-images.githubusercontent.com/74972604/174820747-5cc9742c-a4e4-435d-9ed9-9ee31ed71785.png)

**Comment by 838239178** [comment]
client_id 为官网获取的AK

这肯定是你复制出问题了 检查空格之类的

**Comment by dierwang101** [comment]
> 

嗯，我也是AK和SK写反了，感谢回复。
