### ISSUE TITLE
脚本运行显示unknown client id

### ISSUE THREAD

**Issue by ChampionChann** [838239178/tk-auto-study#85]
### 内容
以下是我的配置文件截图，有填百度图片识别api和secret
![image](https://user-images.githubusercontent.com/74972604/174711923-82d43096-18ba-4117-bb16-23a61d3807cd.png)

以下是我的运行日志：
## 开始执行... 2022-06-21 11:41:08

[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:使用 OCR baidu_image
[INFO]:开始多人打卡，人数8
[INFO]:正在登录尾号1589
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号0061
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号4071
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号1587
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号0630
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号1582
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号5776
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:正在登录尾号6563
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:unknown client id
[WARNING]:正在重试, 次数:4
[INFO]:消息推送成功

**Comment by ChampionChann** [comment]
![image](https://user-images.githubusercontent.com/74972604/174727162-365ff35f-a38b-4f3d-9447-4733f8616a60.png)
本地报错日志

**Comment by ChampionChann** [comment]
![image](https://user-images.githubusercontent.com/74972604/174727932-38cfdb84-2352-4d50-b14c-ded725c60315.png)
本地运行日志

**Comment by 838239178** [comment]
duplicate #85
