### ISSUE TITLE
ocr_type   这个里面填什么内容

### ISSUE THREAD

**Issue by 17850773959** [838239178/tk-auto-study#86]
### 内容

ocr_type   这个里面填什么内容

**Comment by 17850773959** [comment]
把ocr_type删除跑是跑起来了就是打卡出现错误

**Comment by 838239178** [comment]
GitHub action上因为IP问题很难完成打卡，详情见#65

**Comment by 17850773959** [comment]
> GitHub action上因为IP问题很难完成打卡，详情见#65

ocr_type这个里面填什么

**Comment by 838239178** [comment]
https://github.com/838239178/tk-auto-study#%E5%8F%AF%E9%80%89%E8%AF%86%E5%88%AB%E7%B1%BB%E5%9E%8B

**Comment by 17850773959** [comment]
![image](https://user-images.githubusercontent.com/99230293/174930632-733c2b82-f628-4ef3-9fff-63c88564956d.png)
没看懂什么意思

**Comment by 838239178** [comment]
可填baidu_image 等

**Comment by 17850773959** [comment]
> 可填baidu_image 等

不懂是什么

**Comment by 17850773959** [comment]
> 可填baidu_image 等

可以出个安装在电脑上的教程吗，因为我不太会光看文字有些困难。
