### ISSUE TITLE
百度 api qps 限流

### ISSUE THREAD

**Issue by dawnli-github** [838239178/tk-auto-study#90]
### 使用的Python版本

```

### 使用的发行版本

```

### 运行平台

local/server

### 问题描述

状态: 失败

信息 验证码解析失败,请尝试更换方式或发issue寻求帮助

### 运行日志

[WARNING]:获取验证码失败，原因:Open api qps request limit reached
[WARNING]:正在重试, 次数:0
[WARNING]:获取验证码失败，原因:Open api qps request limit reached
[WARNING]:正在重试, 次数:1
[WARNING]:获取验证码失败，原因:Open api qps request limit reached
[WARNING]:正在重试, 次数:2
[WARNING]:获取验证码失败，原因:Open api qps request limit reached
[WARNING]:正在重试, 次数:3
[WARNING]:获取验证码失败，原因:Open api qps request limit reached
[WARNING]:正在重试, 次数:4
[INFO]:消息推送成功
[ERROR]:异常信息: 验证码解析失败,请尝试更换方式或发issue寻求帮助

### 其他补充

状态: 失败

信息 验证码解析失败,请尝试更换方式或发issue寻求帮助

**Comment by 838239178** [comment]
这是你百度APi识别限流了

**Comment by dawnli-github** [comment]
我使用次数很少不知道为啥会被限制，是不是百度api不让用了还是我自己的问题嘞

**Comment by dawnli-github** [comment]
可以了，要实名认证领取一下免费资源

**Comment by 838239178** [comment]
现在百度发病 把以前的数据全清空了 要重新实名认证 否则原来的key都会返回限流
