### ISSUE TITLE
在Centos上执行时出现以下问题，似乎是缺少动态库，不知如何解决

### ISSUE THREAD

**Issue by abin-zh** [838239178/tk-auto-study#91]
### 内容

<details>
[root@VM-0-2-centos tk-auto-study]# python3 main.py
[INFO]:你正在使用本地服务,请确保填写了配置文件
[INFO]:自动学习开始
[INFO]:使用 OCR tesseract
[INFO]:开始多人打卡，人数814
[INFO]:正在登录尾号9566
/root/tk-auto-study/ocr_module/tesseract/ocr-x86_64-linux-gnu: error while loading shar               ed libraries: libtesseract.so.4: cannot open shared object file: No such file or direct               ory
[WARNING]:获取验证码失败，原因:ocr 识别失败，错误代码127
[WARNING]:正在重试, 次数:0
/root/tk-auto-study/ocr_module/tesseract/ocr-x86_64-linux-gnu: error while loading shar               ed libraries: libtesseract.so.4: cannot open shared object file: No such file or direct               ory
[WARNING]:获取验证码失败，原因:ocr 识别失败，错误代码127
[WARNING]:正在重试, 次数:1
/root/tk-auto-study/ocr_module/tesseract/ocr-x86_64-linux-gnu: error while loading shar               ed libraries: libtesseract.so.4: cannot open shared object file: No such file or direct               ory
[WARNING]:获取验证码失败，原因:ocr 识别失败，错误代码127
[WARNING]:正在重试, 次数:2
/root/tk-auto-study/ocr_module/tesseract/ocr-x86_64-linux-gnu: error while loading shar               ed libraries: libtesseract.so.4: cannot open shared object file: No such file or direct               ory
[WARNING]:获取验证码失败，原因:ocr 识别失败，错误代码127
[WARNING]:正在重试, 次数:3
^CFalse
[WARNING]:消息推送失败，原因：请勿频繁推送相同内容
[ERROR]:异常信息: 请阅读异常提醒，如果无法解决请截图日志发issue)：
===============================================
[root@VM-0-2-centos tesseract]# ldd ocr-x86_64-linux-gnu
./ocr-x86_64-linux-gnu: /lib64/libm.so.6: version `GLIBC_2.27' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.25' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.29' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.33' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.28' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.18' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.34' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
./ocr-x86_64-linux-gnu: /lib64/libc.so.6: version `GLIBC_2.32' not found (requir                      ed by ./ocr-x86_64-linux-gnu)
        linux-vdso.so.1 =>  (0x00007ffc6266a000)
        libtesseract.so.4 => not found
        liblept.so.5 => not found
        libssl.so.3 => not found
        libcrypto.so.3 => not found
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f963a01c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9639d1a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f963994c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f963a8fb000)
</details>

**Comment by 838239178** [comment]
@sqlpxc 提供一下需要安装的依赖

**Comment by sqlpxc** [comment]
看起来好像和glibc有点关系，这个项目编译musl-libc有点麻烦，可以看看网上的说法安装一下新版本的glibc，还有就是要安装tesseract依赖，因为内部有使用openssl，如果没有的话也要安装一下 @838239178 @abin-zh

**Comment by sqlpxc** [comment]
具体安装命令每个发行版有点不一样，但是一般网上都能找到

**Comment by 838239178** [comment]
@sqlpxc 为什么我在windows下无需安装任何以来就能够运行呢

**Comment by sqlpxc** [comment]
@838239178 因为windows下我是全部静态链接编译了，linux下因为上游库的问题没有静态链接

**Comment by 838239178** [comment]
Linux自带Tesseract的源程序包。在Linux本地安装步骤如下。

下载图像格式依赖
```
sudo apt-get install libpng12-dev
sudo apt-get install libjpeg8-dev
sudo apt-get install libtiff5-dev
```
下载zlib1g依赖
```
sudo apt-get install zlib1g-dev
```
下载图像处理开发库依赖
```
sudo apt-get install libleptonica-dev
sudo apt-get install libleptonica-dev
```
下载tesseract 光学字符识别核心开发库依赖
```
sudo apt install libtesseract-dev
```
安装Tesseract
```
sudo apt install tesseract-ocr
```
————————————————
版权声明：本文为CSDN博主「高自强的博客」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_33429968/article/details/88830566
